### ISSUE TITLE
Paginated collections / cursors?

### ISSUE THREAD

**Issue by ashaffer** [heroku/react-refetch#117]
Sorry I feel like I must be missing something, but how do you deal with the case of a paginated collection? I'd like to be able to inject my component with a function it can use to request additional items from a collection (e.g. for infinite scroll), but I can't seem to find a way to do it.

I'd like it to look something like:

```javascript
connect(props => ({
  things: `/path/to/things`,
  moreThings: nextPageToken => ({
    things: `/path/to/things?nextPageToken=${nextPageToken}`
  })
}))
```

But obviously that doesn't work. Is there some way of doing this i'm not seeing?

**Comment by ryanbrainard** [comment]
Are you calling this.props.moreThings(nextPageToken) in your component? It looks like they should work.

With that said, I might recommend passing in the page token in from props (instead of using a function) by changing the URL in the browser. It's up to you and your situation, but I find holding that state in the URL and passing it down through props can be nice for bookmarking and sharing links.

**Comment by ashaffer** [comment]
Doesn't that replace `things` with the result of `moreThings`? I'd like it to concatenate the two.

**Comment by ryanbrainard** [comment]
Ah, I see what you're trying to do now. Yes, it would get replaced. See my comment at https://github.com/heroku/react-refetch/issues/113#issuecomment-211615973 that would also help in this case. A workaround would probably be to store the value in an external variable and then do a transformation (in a 'then' handler) to append to the previous value.

**Comment by ryanbrainard** [comment]
You might be able to use a combination of https://github.com/heroku/react-refetch/pull/122 and the `then` suggestion above for this. Please try it out and let me know if that works for you. Closing this for now.
