### ISSUE TITLE
Support for HTTP 304 status to work with Rails weak etags

### ISSUE THREAD

**Issue by BilalBudhani** [heroku/react-refetch#142]
`react-refetch` treats `304` response from Rails 5 as `200` and considers body as json. Whereas, `304` doesn't return any body and so the whole thing breaks. Can we return previously returned `200` response in case of `304` status?

**Comment by ryanbrainard** [comment]
According to https://github.com/github/fetch/issues/241, Chrome and Firefox should theortically convert the 304 into a 200. What browser and fetch implementation are you using? We should probably also expose the `cache` option for fetch.

**Comment by BilalBudhani** [comment]
@ryanbrainard Oh, I see. I'm using this library in React Native that's the reason I'm facing this problem.

**Comment by ryanbrainard** [comment]
I see, it would be best to fix it by using a `fetch` impl that does the right thing, but if it's a simple fix in react-refetch to handle the status correctly, I'd be open to a pull request. However, I think the tricky part is going to be retrieving the cached body -- does your `fetch` handle that?

**Comment by objectiveSee** [comment]
@ryanbrainard did you ever configure the network request to correctly retrieve the cached body? Thanks!

**Comment by ryanbrainard** [comment]
@objectiveSee No, sorry, I haven't.

**Comment by objectiveSee** [comment]
It's unclear whether you need to set the outgoing request's etag headers manually or not

**Comment by ryanbrainard** [comment]
Since this is handled correctly in browsers, I think the easiest solution here is going to be to wrap `fetch` with a caching layer to handle this in other environments (e.g. React Native). Similar to this (but handle the headers and such):

https://github.com/heroku/react-refetch#on-changing-the-fetch-and-request-implementations

I'm going to close this issue since there's not a change needed in this lib; however, if someone would like to update the readme with instructions or an example, I'd be happy to accept a PR.
