### ISSUE TITLE
Add option to dismiss a created promise back to the undefined state

### ISSUE THREAD

**Issue by Soul-Burn** [heroku/react-refetch#146]
When using a lazy fetch directive (e.g "post like"), the promise is in one of 4 major states:
- Fetch was not yet called. The generated promise is undefined. e.g before pressing the like button. The like button appears.
- Fetch was called and pending. The promise exists and is in state loading. A loading icon appears.
- Fetch failed. An error message is reported.
- Fetch succeeded. A success message/dialog might be reported.

The following transitions are currently possible.
- Undefined -> Loading
- Loading -> Failed/Success
- Failed/Success -> Loading

However, there's no way transition to the original undefined state to show the transaction has concluded. Therefore, the code has to include additional state to show that this transaction of pressing "like" has concluded but still have to test both that state and the existence of the promise.

I would like to have the ability to dismiss a lazy promise, returning it to the undefined state or otherwise have the promise always existing in some "unstarted" state so we don't have to check multiple conditions for the same logical state.

Note: It _is_ possible to include a second state and use one time callbacks at the end of promises, but it requires more fiddling and state than is expected.

**Comment by ianstormtaylor** [comment]
I'm also curious about this. My use case is for easily rendering an inline loading/validation indicator at the right side of an `<input>` that shows that a field is saving/saved/errored after you've typed in it.

It's fairly easy to get these states:

```js
const isEmpty = !updateFetch
const isSaving = updateFetch && updateFetch.pending
const isErrored = updateFetch && updateFetch.rejected
const isSaved = updateFetch && updateFetch.fulfilled
```

But there's no easy way to "reset" (or potentially better named "unset") the lazy fetch after a bit of time to have the lifecycle restart itself for future edits.

I think it would be nice to have an imperative API for it—something as simple as:

```js
updateFetch.reset()
```

But, for consistency and simplicity, it would also be nice to add an automatic reset window in the request object, using an interval after succeeding, like:

```js
{
  ...,
  resetInterval: 5000
}
```

Such that the timer begins after the fetch succeeds.

Just a concept, open to a different way to solve it simply though!

**Comment by ryanbrainard** [comment]
I recently ran into this myself, and I solved it by setting the lazy response to null with an "[identity request](https://github.com/heroku/react-refetch#identity-requests-static-data--transforming-responses)". For example:

```jsx
export default connect((props) => ({
  opResponse: {
    value: null, // clear results
  },
  opRequest: (pkg, service, method, args) => ({
    opResponse: {
      url: `${pkg}/${service}/${method}`,
      method: 'POST',
      body: JSON.stringify(args),
    },
  }),
}))(MyComponent)
```

So what happens is that when `MyComponent` first loads, `opResponse` is `fulfilled` with a value of `null`. Then when the `opRequest` function is called, `opResponse` goes to `pending` and `fulfilled` again, but with an actual value this time. Then the next time something causes the mappings in connect to be recalculated (i.e. a change to props or context), `opResponse` is set to `fulfilled` with a value of `null` again. So your states above would become something like this:

```js
const isEmpty = updateFetch && updateFetch.fulfilled && !updateFetch.value
const isSaving = updateFetch && updateFetch.pending
const isErrored = updateFetch && updateFetch.rejected
const isSaved = updateFetch && updateFetch.fulfilled && updateFetch.value
```

Of course this does require you to have something cause the props to change, which might work for you, but if you want it to be more explicit, you could also do something like this:

```jsx
export default connect((props) => ({
  opResponse: {
    value: null, // clear results
  },
  opRequest: (pkg, service, method, args) => ({
    opResponse: {
      url: `${pkg}/${service}/${method}`,
      method: 'POST',
      body: JSON.stringify(args),
    },
  }),
  clearOpResponse: () => ({
    opResponse: {
      value: null, // clear results
    },
  }),
}))(MyComponent)
```

then you can just call `clearOpResponse()` and `opResponse` will be cleared.

I'd rather not doing anything with the a time delay, but you could get fancy with using the `meta.component` in `then()` on the response if you wanted to call something in your component so handle this in a more custom way.'

Please let me know if you think this `value: null` works for you. I've personally found it better to have the PromiseState itself always exist, but have the internal `value` be null rather than having to deal with ever having a null/undefined PromiseState. When @Soul-Burn originally opened this issue, I don't think identity requests (i.e. this ability to set the `value` directly) existed. I'm going to close this for now because I think this solves it, but feel free to re-open if you think there should be more consideration.

**Comment by ianstormtaylor** [comment]
Thanks @ryanbrainard, that does seem like a viable solution! I'll experiment with it and see how it feels, but it seems like it's definitely close enough to warrant not adding more complexity to core.

**Comment by Soul-Burn** [comment]
Yes. This seems like a suitable solution for these kinds of requests. I think I even considered using identity requests, but it seemed like a bit of fiddling.
I don't think it's good to set it to null every time props change, because a different interaction might cause props to change, which in turn might break my interaction.
Therefore, I would still need to test for the two empty cases, like this:
`const isEmpty = !updateFetch || (updateFetch && updateFetch.fulfilled && !updateFetch.value)`
The rest of the code would be simple. I can encapsulate this logic in a function to reduce the boilerplate checks, e.g mapping a fulfilled and `undefined` value to `undefined`.

    mapEmpty(promise) {
        return (promise && promise.fulfilled && promise.value === undefined) ? undefined : promise;
    }
