### ISSUE TITLE
Custom Request Post-Processing

### ISSUE THREAD

**Issue by bbirand** [heroku/react-refetch#18]
I really like this library, and I'd like to try it for a data-intensive app. Currently, I use d3's `csv` method to do this:

```js
// (It's CSV, but GitHub Pages only gzip's JSON at the moment.)
d3.csv("large_dataset.csv", function(error, dat) {
   //work with dat
}
```

I implemented a version with react-refetch, that looks like this:
```js
let AnalysisRefetch = connect((props) => ({
    fetchedData: `large_dataset.csv`
}))(Analysis)
```

But when I look into `this.props.fetchedData`, the promise is rejected with the reason "SyntaxError: Unexpected token ,". 

I imagine this is because refetch was built for fetching JSON objects. But can I plug in a custom parser or so on the returned value? Or have access to the raw response, somehow? Using refetch will make things so much easier!

Thanks

**Comment by bbirand** [comment]
I see now that this is the place where the magic happens:

https://github.com/heroku/react-refetch/blob/019a17057d7af6c22e4c9e160e77d08a11ec41c0/src/components/connect.js#L79

If you can point me in the right direction, I can try to give this a shot.

**Comment by hnordt** [comment]
I would like to suggest something like this:

```js
connect(({ name }) => ({
  barFetch: {
    url: `/foos/${name}.csv`,
    dataType: 'csv' // maybe responseType?
  }
}))
```

**Comment by ryanbrainard** [comment]
I'm all for accepting than just JSON, but I'd kind of like to have it based on the Content-Type header in the response rather than adding a new attribute. That might be wishful thinking since there's always going to be some API that doesn't have the right headers and anyway clients will need to send the Accept header as well. 

Another idea is to have customizable response processors. This is kind of possible now with PromiseState.then(), but since it's defaulting to JSON, it's too late once it gets to then(). 

So, given all this, I'm thinking we should use the response Content-Type if we can, fall through to JSON for backward compatibility, and allow it to be overridden by an attribute. Thoughts?

**Comment by hnordt** [comment]
@ryanbrainard :+1: for Content-Type.

Please look at my enhancers idea: https://github.com/heroku/react-refetch/issues/9#issuecomment-166420907

**Comment by hnordt** [comment]
@ryanbrainard my suggestion on https://github.com/heroku/react-refetch/issues/40#issuecomment-172942228 can handle this

**Comment by ryanbrainard** [comment]
[v1.0.0-beta.0](https://github.com/heroku/react-refetch/releases/tag/v1.0.0-beta.0) has the ability to change the `buildRequest`, `fetch`, and `handle Response` implementations, which should open up a lot of possibilities here. These features are probably a little too low level for everyday post-processing; however, I want people to kick the tires on them and see what can possibly be built on top of them. I'm going to close this issue now so that we can re-frame remaining enhancements in this new context by opening new issues.
