### ISSUE TITLE
Update peerDependency on React

### ISSUE THREAD

**Issue by heyimalex** [heroku/react-refetch#186]
Currently produces a warning with v16. Pretty sure there weren't any breaking changes wrt react-refetch (at least I haven't experienced anything obvious) so it should be safe to bump.

**Comment by ryanbrainard** [comment]
Fixed in https://github.com/heroku/react-refetch/commit/e812392e6e12d47c0d9196342f92720e75cb736c and pre-released in [v1.0.3-0](https://github.com/heroku/react-refetch/releases/tag/v1.0.3-0). This still needs to be tested, so this is just a pre-release, but wanted to get something out there so folks and kick the tires.
