### ISSUE TITLE
Accessing the response body in case of reject

### ISSUE THREAD

**Issue by gioiafueter** [heroku/react-refetch#211]
Hi!

I receive a response with status 404, and inside the body of the response looks like this:
{"errors":[{"title":"Not Found","detail":"No known customer with any provided ID","status":"404"}]}

I need to display the title and detail, but the reason contains:
tokensFetch.reason Error
    at newError (errors.js:6)
    at handleResponse.js:24

which is unhelpful to the user.... 

I tried using the meta, but the body is not available there either... How can I access it?

Thank you very much!

**Comment by ryanbrainard** [comment]
The problem is that in that response `errors` is plural, but the lib is [looking for `error` (or `message`) singular](https://github.com/heroku/react-refetch/blob/48af31d30f0be045d0d8586b49f8d8da1ca1f7eb/src/utils/errors.js#L7-L17). You can either change the response or [override `handleResponse`](https://github.com/heroku/react-refetch#setting-defaults-and-hooking-into-internal-processing).  to process it as you see fit. Using `meta` will not give you access to response bodies.

**Comment by ryanbrainard** [comment]
Also, if you do find a nice way to generalize this case of an errors array, feel free to open a PR to change how `parse(cause)` works. I'm not sure if we should take the first error, map over them, or what, but opening a PR could generate some discussion.
