### ISSUE TITLE
Is it possible to use a callback of a request?

### ISSUE THREAD

**Issue by StudioSpindle** [heroku/react-refetch#245]
I would like to change the state of a component based on the response of a PUT request. Whether it is successful or unsuccessful for that matter.

The following example is an example in a form. When a user submits the form it should then fire off a PUT. If the PUT response is fulfilled, it should reset the form. Otherwise the user should be able to retry.

```js
const MyForm = ({ settingsPut, settingsPutResponse }) => {
  const submitForm = (values, { setSubmitting, resetForm }) => {
    settingsPut(true);

    // something like this does not work
    if (settingsPutResponse && settingsPutResponse.fulfilled) {
      resetForm();
      setSubmitting(false);
    }
  };

  return (
      <div>
        // here the PUT response works, but It can't be set to reuse it in the submit function
        {settingsPutResponse && settingsPutResponse.fulfilled && (
          <p>The fetch was succesful!</p>
        )}
     // ...
```

Would it perhaps be possible to use a callback in the PUT, as follows:

```js
const MyForm = ({ settingsPut, settingsPutResponse }) => {
  const submitForm = (values, { setSubmitting, resetForm }) => {

    // Would a callback like this be possible? 
    settingsPut(true, (response) => {
      if (response && response.fulfilled) {
        resetForm();
        setSubmitting(false);
      }
      if (response && !response.ok) {
        // retry the submit automatically
      }
    });

    // or
   settingsPut(true).then((response) => {
      if (response && response.fulfilled) {
        resetForm();
        setSubmitting(false);
      }
      if (response && !response.ok) {
        // retry the submit automatically
      }
    });
  };

  return (
     // ...
```

I've created an codesandbox example here: https://codesandbox.io/s/quizzical-johnson-dberw

**Comment by StudioSpindle** [comment]
Might have found it.

The `handleResponse: function (response) {}` can be used, as described under [setting defaults and hooking into internal processing](https://github.com/heroku/react-refetch#setting-defaults-and-hooking-into-internal-processing)

**Comment by ryanbrainard** [comment]
Instead of trying to call a callback or do anything like that in `render()`, I recommend using the `componentDidUpdate()` hook to act upon changes to `settingsPutResponse`. Something like:

```js
  componentDidUpdate() {
    if (settingsPutResponse && settingsPutResponse.fulfilled) {
      resetForm();
      setSubmitting(false);
    }
  }
```

However, `resetForm()` and `setSubmitting(false)` should probably be an atomic update to avoid partial state changes.

Better yet, don't even reset your form, but instead, just re-render it. A cheap way to do that is to wrap it in a container element that has a `key` attribute that changes.

I would strongly recommend *not* using `handleResponse` to accomplish this. It sounds like you're trying to treat a `PromiseState` as a `Promise`, but they are not the same thing. Remember, your component is rendering the state of the promise at a point in time, so a callback doesn't really make sense on something that will be re-rendered many times over.

**Comment by StudioSpindle** [comment]
Thanks for the feedback. Indeed handleResponse is not correct.

In general, is there no way to handle the response of the fetch as similar to the code examples given?

**Comment by ryanbrainard** [comment]
The closest you can get to doing that is using the `withRef` option and then tacking on an `andThen` to the request to call methods on the component; however, I'd recommend just handling it in `componentDidUpdate`.
