### ISSUE TITLE
Warning shown when component is unmounted while refetch request is pending

### ISSUE THREAD

**Issue by ardalann** [heroku/react-refetch#62]
If a user clicks on a button that unmounts the current component while the component's refetch request is pending, the following warning will be shown in the console after the refetch request is complete:

`Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Refetch.connect(PostList) component.`

Are we supposed to cancel the refetch request within `componentWillUnmount()` ? How can we do that?

**Comment by eyalw** [comment]
+1

This can be fixed within RR with checking "isMounted()", but today it's considered an anti-pattern.
A better solution will be to use a cancellable promise (which will not call "then()" if cancel()ed on componentWillUnmount()).

**Comment by ryanbrainard** [comment]
We currently don't keep a tally of in-flight promises, so I'd rather just maintain our own `_isMounted` property (since `isMounted()` is going away) and skip setting the state when the promise is settled. Even the cancelable promise [Facebook recommends](https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html) is not really cancelling anything, but rather just ignoring the result, so not too different and would require more bookkeepping.

**Comment by eyalw** [comment]
Sounds good

**Comment by ryanbrainard** [comment]
Fixed by #87
