### ISSUE TITLE
Static Data not immediately fulfilled?

### ISSUE THREAD

**Issue by neezer** [heroku/react-refetch#63]
Maybe I'm misunderstanding something, but I'd assume that [static data definitions](https://github.com/heroku/react-refetch#identity-requests-static-data--transforming-responses) like the following:

```es6
export default connect((props) => ({
  userFetch: { value: { id: 1, name: 'Tigger' }}
})(Component);
```

... would be available immediately, say, in the initial render:

```es6
render() {
  const user = this.props.userFetch.value;
}
```

However, it seems that on the initial render, `this.props.userFetch.pending` is `true`. I can't seem to get access to the static data until `componentWillReceiveProps`.

Shouldn't the `PromiseState` for a static data definition be immediately fulfilled?

**Comment by ryanbrainard** [comment]
@neezer This is expected behavior. It was a bit of a judgement call during implementation of identity requests to make them either A) skip `pending` or B) act like any other request and go through the full lifecycle. I went with B for consistency; however, I would not be too opposed to changing this. I do see the value of your use case. Going to leave this open for comments from others that were involved in the original PR:

1. Is there good (real world) reason to have the identity request go through the `pending` state? (i.e. keep behavior we have today)
2. What would you expect to happen? Skip pending of go through `pending`?
3. Would there be any reason to make this configurable?

cc: @jsullivan @hburrows @georgebonnr @ashtuchkin @hnordt

**Comment by ryanbrainard** [comment]
Released in https://github.com/heroku/react-refetch/releases/tag/v0.7.0-beta.3
