### ISSUE TITLE
ReactRefetch IE 11 error > Error: Object doesn't support property or method 'assign'

### ISSUE THREAD

**Issue by Gui-Jun** [heroku/react-refetch#82]
Error: Object doesn't support property or method 'assign' with IE 11
Compiled with webpack

Please fix for bug.

Come to search seems to be following method.

https://github.com/react-toolbox/react-toolbox/commit/25bc10c4b9808cef681ee2cb55b2015ce9e3e750

Thanks.

**Comment by ryanbrainard** [comment]
We need to add documentation about which polyfills are needed. See https://kangax.github.io/compat-table/es6/#test-Object_static_methods_Object.assign, but I personally use [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/) in my projects.

**Comment by Gui-Jun** [comment]
Ryan thanks!
I have been fixed for Object.assign issue that you suggest for using babel-polyfill.

**Comment by felixgirault** [comment]
Hi,
I'm sorry to reopen this issue but I had some trouble solving the problem.

I find `babel-runtime` cleaner than `babel-polyfill`, and I thought it was doing exactly the same thing in the end.
In fact it does, but in a much more limited scope. For example, given this webpack config:

```js
{
  module: {
    loaders: [
      {
        loader: 'babel',
        test: /\.js$/,
        exclude: /node_modules/
      }
    ] 
  }
}
```

...and the `babel-plugin-transform-runtime` set up correctly, the code from `react-refetch` is not polyfilled as babel doesn't run on `node_modules/`.

Finally, I ended up using `babel-polyfill` and it works like a charm, but I found something quite strange in the generated code from `react-refetch` (v7.1).

In `lib/connect.js`, `Object.assign` seems to be polyfilled at line 5:

```js
var _extends = Object.assign || function (target) { for (var i = 1; i < arguments.length; i++) { var source = arguments[i]; for (var key in source) { if (Object.prototype.hasOwnProperty.call(source, key)) { target[key] = source[key]; } } } return target; };
```

`_extends` is then only used at line 187, but everywhere else `Object.assign` is used directly.
It seems like the code is kinda polyfilled but actually not so much ^^ 
Do you know what could cause this ?
And do you plan on shipping `react-refetch` already polyfilled in the future ?

Anyway, thank you for the lib, and sorry for such a long post ;)

**Comment by ryanbrainard** [comment]
That `_extends` is from the transcompilation during the build process. What you are seeing on Line 189 in the transcompiled source is coming from https://github.com/heroku/react-refetch/blob/877e8d5fab391e984c08fd20d5b18d94cdaad276/src/components/connect.js#L141-L144 in the original source. All other uses of `Object.assign` are in the original source itself. 

> And do you plan on shipping react-refetch already polyfilled in the future ?

No, I was not planning on it. My thinking was that I wanted to give people the option of what polyfills to use and not conflict with other polyfills. Similar to the direction we want to take with allowing you to bring your own `fetch` implementation. My aim is not to introduce pain for developers, so if bundling in an custom `assign` function would make it better, I'm not fundamentally opposed to it, it just felt unnecessary. @passcod had originally done that in https://github.com/heroku/react-refetch/pull/76 and I had him revert it, but I'd like to hear more thoughts on this (partiularly what is done in other JS projects -- TBH, I don't use JS very much outside of this project)

**Comment by nfcampos** [comment]
There are basically 4 options:
1) depend on polyfills and include them (we can't do this, the user must be the one to choose what polyfills to use)
2) depend on polyfills and warn the use he has to include them
3) use implementations of these functions from a dependency (we don't have to test and maintain them)
4) write our own implementations (maybe the bundle size is smaller, maybe not)

Most libraries seem to do 3 or 4. I'm not a big fan of 4 because it's one more thing to maintain. Doing 3 might not increase the bundle size for the user if a) the dependency we include for it is as small as what we would write or b) it's a dependency that is common enough that some users would already be including it anyway (eg. single methods from lodash).
We can also do 2) and either add warnings in the README or runtime warnings telling you to include the polyfill if it isn't there?

**Comment by felixgirault** [comment]
@ryanbrainard I totally understand your point on letting people use what they want as polyfills. But on the other hand I'm usually expecting a compiled dependency to work out of the box.
In fact, letting people polyfill `fetch` makes a lot of sense to me, but `Object.assign` is such a small utility that it is indeed a little annoying to have to include it myself. As @nfcampos said, it could easily be included in the build without increasing the bundle size too much.

@nfcampos Adding warnings is a good idea, that's one of the things I really like in React.

Maybe a good compromise would be to polyfill `Object.assign` in the build, but also include source files in the npm package so that the user can build its own version if needed ?

**Comment by passcod** [comment]
If we start to include polyfills, we better make sure that we also include polyfills for every feature we use that's not supported in [browsers we want to support]. And draw that line.

**Comment by passcod** [comment]
Pinging here as it's related. I have added some wording regarding polyfills in my PR: https://github.com/heroku/react-refetch/pull/76/files#diff-04c6e90faac2675aa89e2176d2eec7d8R19

**Comment by felixgirault** [comment]
Thank you for adding that in the README, it will probably save you and the users some time :)
