### ISSUE TITLE
POST action does not trigger the same request

### ISSUE THREAD

**Issue by gaugau** [heroku/react-refetch#88]
When the first submit attempt failed (rejected), the user re-enter the details and execute `upgradePlan` again, but there was no HTTP request performed. Because, it's a POST request so I don't expect that it should be cached?! 

```javascript
submit() {
   this.props.upgradePlan(data)
}
...
export default connect(props => ({
  tokenFetch: `/api/v1/organisations/${props.params.organisationId}/payments/token`,
  upgradePlan: data => ({
    upgradePlanResponse: {
      url: `/api/v1/organisations/${props.params.organisationId}/payments/upgrade`,
      method: 'POST',
      body: JSON.stringify({ data })
    }
  })
}))(SubscriptionUpgrade)

```

**Comment by ryanbrainard** [comment]
It's probably not being cached per se, but not firing the request again because the URL and data didn't change. Try adding `force: true` into your request and it should work. Alternatively, you can use `comparison:` if you want finer-grained control when it fires again. 

Re-open this issue if you're still having problems.
