### ISSUE TITLE
Type check all mapping values (not just defaults)

### ISSUE THREAD

**Issue by ryanbrainard** [heroku/react-refetch#91]
If a mapping is supplied as a default, it gets type checked, not not if provided inside of connect. We should do the same in both places.

**Comment by nfcampos** [comment]
type check then, catch, andThen and andCatch as well?

**Comment by ryanbrainard** [comment]
Yeah, make sure they are functions. Any reason not to?

**Comment by nfcampos** [comment]
since currently we ignore any values for these 4 that are not functions this would be a breaking change (as in it might break someone's app). But i still think we should do it

**Comment by ryanbrainard** [comment]
> this would be a breaking change

We're incrementing to 1.0.0, so let's do as part of that

**Comment by nfcampos** [comment]
also, how do you feel about moving the type check definitions to a separate file, `connect.js` is getting kind of crowded, and it's not like you need to see the type checks to understand the rest of the code?

**Comment by ryanbrainard** [comment]
> how do you feel about moving the type check definitions to a separate file

+1. We should probably go through and do some overall hoursekeeping.

**Comment by nfcampos** [comment]
btw, something i've been meaning to do is add a pure option like react-redux has (only recompute the mappings when props (or context) actually changed (compared with shallowEqual), also only rerender when same thing is true). Any reason why you didn't bring that over when you forked from react-redux?
(I remembered this now because with the defaults assignment, now we add type checking for each mapping, etc it probably gets kind of expensive when you have lots of mappings...)

**Comment by ryanbrainard** [comment]
> pure option like react-redux. .. Any reason why you didn't bring that over when you forked 

I think I left it out for immediate simplicity with the intention of adding it back, but never did.

**Comment by nfcampos** [comment]
I've opened a PR for the `pure` optimisation #94

**Comment by nfcampos** [comment]
I've made these changes regarding type checking individual mappings, etc. I'll open a PR soon.

**Comment by ryanbrainard** [comment]
Closed by #96
